dependencies:
  - all: ["poetry.lock", "!**/*.py"]

documentation:
  - any: ["**/*.md"]
    all: ["!**/*.py", "!.github/**/*"]

github structure:
  - any: [".github/**/*"]
    all: ["!**/*.py"]

test:
  - any: ["tests/**/*"]
    all: ["!glocaltokens/**/*"]
