name: "Setup Python Environment"

runs:
  using: "composite"
  steps:
    - name: Setup environment in bash
      id: env-bash
      shell: bash
      run: |
        PYTHON_USER_BASE="$(python -m site --user-base)"
        echo "$PYTHON_USER_BASE/bin" >> $GITHUB_PATH
        echo "pip-user-base=$PYTHON_USER_BASE" >> $GITHUB_OUTPUT

outputs:
  pip-user-base:
    value: ${{ steps.env-bash.outputs.pip-user-base }}
