name: "Common steps to install and cache dependencies"

inputs:
  python-version:
    description: "Python version to set up"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: |
        uv python install ${{ inputs.python-version }}
        echo "PYTHON_VERSION=$(uv run python -c 'import platform; print(platform.python_version())')" >> "$GITHUB_ENV"

    - name: Install dependencies with uv
      shell: bash
      run: uv sync
