name: "Common steps to install and cache dependencies"

inputs:
  python-version:
    description: "Python version to set up"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: yezz123/setup-uv@v4

    - name: Cache project dependencies
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: deps-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Install dependencies with uv
      shell: bash
      run: |
        uv sync
