name: Manage labels

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3.1.0
        with:
          skip-delete: true
