on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy requirements.txt
        run: |
          ls $GITHUB_WORKSPACE
          cp $GITHUB_WORKSPACE/requirements.txt $GITHUB_WORKSPACE/github/workspace/docs/glocaltokens/requirements.txt
      - uses: seanzhengw/sphinx-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
          source_dir: 'glocaltokens'
