on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy requirements.txt
        working-directory: $GITHUB_WORKSPACE
        run: |
          cp requirements.txt glocaltokens/
      - uses: seanzhengw/sphinx-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
          source_dir: 'glocaltokens'
